### ISSUE TITLE
All assets are stored inside a 'Resources' folder

### ISSUE THREAD

**Issue by VapidLinus** [doctor-GAMES/Faux#11]
This absolutely shouldn't be done. Only files that are going to be loaded using Resources.Load() are to be placed inside the Resources folder.
When Unity compiles a game, it leaves out any unused assets to save space and make the game smaller. However, Unity always includes all assets inside the 'Resources' folder and it's subfolders.

**Comment by solbjorg** [comment]
Aw shieeeeeeeet

**Comment by VapidLinus** [comment]
You guys had some trouble deciding who should do this.
"FROFF YOU DO THIS"
"NEVERMIND, BIRK, YOU DO THIS"
"PLZFIX IT BIRK"
"OKAY NEVERMIND BIRK, DON'T FIX IT"
"I WILL JUST DO IT MYSELF"
"DID IT"
